// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVEKsyr9OZhaBTrLX9wG7LAKDvfKUkrqo',
    appId: '1:1033336250244:web:bb114493e51db3b7ab07d1',
    messagingSenderId: '1033336250244',
    projectId: 'food-2cd96',
    authDomain: 'food-2cd96.firebaseapp.com',
    storageBucket: 'food-2cd96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6xt19GB_onmoaO_8obhYdzIkhfjx59Fw',
    appId: '1:1033336250244:android:72686223feb3f0edab07d1',
    messagingSenderId: '1033336250244',
    projectId: 'food-2cd96',
    storageBucket: 'food-2cd96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDSa5P4XelHuQnpQdNy-lLg41wF0WFtrA',
    appId: '1:1033336250244:ios:2d90a9aa449dbb82ab07d1',
    messagingSenderId: '1033336250244',
    projectId: 'food-2cd96',
    storageBucket: 'food-2cd96.appspot.com',
    iosBundleId: 'com.example.foodTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDSa5P4XelHuQnpQdNy-lLg41wF0WFtrA',
    appId: '1:1033336250244:ios:2d90a9aa449dbb82ab07d1',
    messagingSenderId: '1033336250244',
    projectId: 'food-2cd96',
    storageBucket: 'food-2cd96.appspot.com',
    iosBundleId: 'com.example.foodTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVEKsyr9OZhaBTrLX9wG7LAKDvfKUkrqo',
    appId: '1:1033336250244:web:b9ae4b9896314b7bab07d1',
    messagingSenderId: '1033336250244',
    projectId: 'food-2cd96',
    authDomain: 'food-2cd96.firebaseapp.com',
    storageBucket: 'food-2cd96.appspot.com',
  );
}
